### ISSUE TITLE
As a logged-in user, I want to create a new recipe so that I have it in my personal cookbook for further use.

### ISSUE THREAD

**Issue by Alzameister** [sopra-fs24-group-22/Let-Them-Cook#20]
**Acceptance criteria**
- A user can add a recipe in the recipes tab, where an overview of all recipes is shown.
- Adding a new recipe prompts the user to add a recipe name, all of its ingredients and the required cooking steps.
- Optionally, the user can define the recipe as public so that it is shown to all other users in the recipe tab.

**Tasks**

- [x] #52
- [x] #53
- [x] #54
- [x] #55

**Comment by giangyger** [comment]
```[tasklist]
### My tasks
- [ ] https://github.com/octo-org/octo-repo/issues/45
- [ ] Draft task
```
